#!/bin/sh


set -e


cd "$(dirname "$0")/.."


if [ "$RAILS_ENV" = "test" ] || [ "$RACK_ENV" = "test" ]; then

  script/setup

else

  export RAILS_ENV="test" RACK_ENV="test"

  script/update

fi


echo "===>>> Running tests..."


if test -n "$1"; then

  bin/rspec "$1"

else

  bin/rspec

fi
